config/routes.rb
Rails.application.routes.draw do
  resources :meters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meter.rb
class Meter < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meters_controller.rb
class MetersController < ApplicationController
  before_action :set_meter, only: [:show, :edit, :update, :destroy]

  # GET /meters
  # GET /meters.json
  def index
    @meters = Meter.all
  end

  # GET /meters/1
  # GET /meters/1.json
  def show
  end

  # GET /meters/new
  def new
    @meter = Meter.new
  end

  # GET /meters/1/edit
  def edit
  end

  # POST /meters
  # POST /meters.json
  def create
    @meter = Meter.new(meter_params)

    respond_to do |format|
      if @meter.save
        format.html { redirect_to @meter, notice: 'Meter was successfully created.' }
        format.json { render :show, status: :created, location: @meter }
      else
        format.html { render :new }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meters/1
  # PATCH/PUT /meters/1.json
  def update
    respond_to do |format|
      if @meter.update(meter_params)
        format.html { redirect_to @meter, notice: 'Meter was successfully updated.' }
        format.json { render :show, status: :ok, location: @meter }
      else
        format.html { render :edit }
        format.json { render json: @meter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meters/1
  # DELETE /meters/1.json
  def destroy
    @meter.destroy
    respond_to do |format|
      format.html { redirect_to meters_url, notice: 'Meter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter
      @meter = Meter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meter_params
      params.require(:meter).permit(:energy_consumed, :total_energy_credits, :energy_credits_rate, :balance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meters_helper.rb
module MetersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meters/_form.html.erb
<%= form_with(model: meter, local: true) do |form| %>
  <% if meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
        <% meter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :energy_consumed %>
    <%= form.number_field :energy_consumed %>
  </div>

  <div class="field">
    <%= form.label :total_energy_credits %>
    <%= form.number_field :total_energy_credits %>
  </div>

  <div class="field">
    <%= form.label :energy_credits_rate %>
    <%= form.number_field :energy_credits_rate %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.number_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meters/edit.html.erb
<h1>Editing Meter</h1>

<%= render 'form', meter: @meter %>

<%= link_to 'Show', @meter %> |
<%= link_to 'Back', meters_path %>

app/views/meters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meters</h1>

<table>
  <thead>
    <tr>
      <th>Energy consumed</th>
      <th>Total energy credits</th>
      <th>Energy credits rate</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meters.each do |meter| %>
      <tr>
        <td><%= meter.energy_consumed %></td>
        <td><%= meter.total_energy_credits %></td>
        <td><%= meter.energy_credits_rate %></td>
        <td><%= meter.balance %></td>
        <td><%= link_to 'Show', meter %></td>
        <td><%= link_to 'Edit', edit_meter_path(meter) %></td>
        <td><%= link_to 'Destroy', meter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meter', new_meter_path %>

app/views/meters/new.html.erb
<h1>New Meter</h1>

<%= render 'form', meter: @meter %>

<%= link_to 'Back', meters_path %>

app/views/meters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Energy consumed:</strong>
  <%= @meter.energy_consumed %>
</p>

<p>
  <strong>Total energy credits:</strong>
  <%= @meter.total_energy_credits %>
</p>

<p>
  <strong>Energy credits rate:</strong>
  <%= @meter.energy_credits_rate %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @meter.balance %>
</p>

<%= link_to 'Edit', edit_meter_path(@meter) %> |
<%= link_to 'Back', meters_path %>